[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.install]
cmds = [
    "cd backend",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd backend",
    "python3 manage.py collectstatic --noinput",
    "python3 manage.py migrate --noinput"
]

[start]
cmd = "cd backend && python3 -m gunicorn flower_farm_api.wsgi:application --bind 0.0.0.0:$PORT" 