[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "cd backend",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd backend",
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput"
]

[start]
cmd = "cd backend && python -m gunicorn flower_farm_api.wsgi:application --bind 0.0.0.0:$PORT" 