[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
    "cd frontend",
    "npm ci"
]

[phases.build]
cmds = [
    "cd frontend",
    "npm run build"
]

[start]
cmd = "cd frontend && npx serve -s dist -l $PORT" 