# Generated by Django 5.2.3 on 2025-06-20 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initials",
                    models.CharField(
                        help_text="Player initials (3 uppercase letters)",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_initials",
                                message="Initials must be exactly 3 uppercase letters",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                ("score", models.IntegerField(help_text="Game score points")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the score was submitted"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Score",
                "verbose_name_plural": "Game Scores",
                "ordering": ["-score", "-timestamp"],
            },
        ),
    ]
